theme[main_bg]=""
theme[main_fg]="#e5dbfa"
theme[title]="#ffffff"
theme[border]="#673ab7"
theme[inactive]="#2a1a40"
theme[hi_fg]="#f3e5f5"
theme[selected_bg]="#4a148c"
theme[selected_fg]="#ffffff"
theme[graph_text]="#9c7cb6"
theme[meter_bg]="#1a0f26"

theme[cpu_box]="#673ab7"
theme[cpu_start]="#4a148c"
theme[cpu_mid]="#7b1fa2"
theme[cpu_end]="#e040fb"

theme[mem_box]="#673ab7"
theme[mem_start]="#311b92"
theme[mem_mid]="#6a1b9a"
theme[mem_end]="#d500f9"

theme[net_box]="#673ab7"
theme[net_start]="#4a148c"
theme[net_mid]="#8e24aa"
theme[net_end]="#f50057"

theme[proc_box]="#2a1a40"
theme[proc_misc]="#ba55d3"

theme[div_line]="#2a1a40"

theme[temp_start]="#4a148c"
theme[temp_mid]="#aa00ff"
theme[temp_end]="#ff007f"

theme[free_start]="#2a123a"
theme[free_mid]="#6a1b9a"
theme[free_end]="#df40ff"

theme[cached_start]="#311b92"
theme[cached_mid]="#6a1b9a"
theme[cached_end]="#e040fb"

theme[available_start]="#4a148c"
theme[available_mid]="#7b1fa2"
theme[available_end]="#df40ff"

theme[used_start]="#311b92"
theme[used_mid]="#8e24aa"
theme[used_end]="#ff00ff"

theme[download_start]="#4a148c"
theme[download_mid]="#8e24aa"
theme[download_end]="#ff00ff"

theme[upload_start]="#311b92"
theme[upload_mid]="#7b1fa2"
theme[upload_end]="#df40ff"

theme[battery_start]="#311b92"
theme[battery_mid]="#6a1b9a"
theme[battery_end]="#df40ff"
